# -*- coding: utf-8 -*-
#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

cyg_logo_small = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAACIUlE"
    "QVQokZWRTWjTABzFX9K0SZuktZ9a9tGOzjq0IM7qmBRFYYUpIghOB4Ke9eJBBA8iiuAugt6U"
    "7TSE+VUPzsvwIohMZegYdd2U6iitW1jWatOkaZomHuoHBQ/1Xf/vx+P/HjLLX8SSZLYtMpdb"
    "e/joiarKaE+EaZoTk+80abY3HEweGWm96gD1DwDA0+f5z4uplXTKHRmendNL5QYAvz/o5jaO"
    "Hw4tzL25fOUmz3MAyCa3Ji3ffeCt8Sfjvfx2bjriEyM+cSC2dTCeHLu1OD2Tr1eLTScFQJaV"
    "pWx65cPVyU/xzMfo0X2JAz0eAN09hXvj44eSZyXlWLYoewK/AYIkaKsd2Oz1emVpo1QNdYb3"
    "AxBEPbZjVzZ7f2hoz8tn4hb7ma5QhAJgAg4LATTqNaG8LpLEwWs3pgDMp18YhgmbZyHHnRod"
    "TT2euXDxHEzTrCjq9bHbgI2xdzCObsoW+NOJhbSRBBOJxJZWheYOFADTAM+7AE2tFgB6W3TQ"
    "6RoG4HD4KItN0+pdYZ8ul4HArx9qWm1nfyLWFz8xcmmgf68g5CVFAcCytFKRy9+lzj6n3+Vq"
    "ZpIAvLx94vXq+TtTBcb9vvRtvkEUGWuRsQq16ltJ/+rzZHRW+FH/Wyso6+7oJpOgqVCw2hCr"
    "+fwr1QXgdCIYcNUZzslQZIePa1m6oWvrGqHWDdpC6KrscdAAyhWZY1nDMFgrQTFsC9C+yP9y"
    "A/gJ+FILflFOO+AAAAAASUVORK5CYII=")
getcyg_logo_smallData = cyg_logo_small.GetData
getcyg_logo_smallImage = cyg_logo_small.GetImage
getcyg_logo_smallBitmap = cyg_logo_small.GetBitmap
getcyg_logo_smallIcon = cyg_logo_small.GetIcon

